### ISSUE TITLE
.pyvimrc example throws errors

### ISSUE THREAD

**Issue by lillian27** [jonathanslenders/pyvim#10]
Traceback (most recent call last):
  File "/Users/lillian/Documents/Projects/feeder/fbase/lib/python2.7/site-packages/pyvim/rc_file.py", line 52, in run_rc_file
    namespace['configure'](editor)
  File "/Users/lillian/.pyvimrc", line 33, in configure
    self.display_unprintable_characters = True
NameError: global name 'self' is not defined

Press ENTER to continue...

pyvim installed in virtualenvvia pip on OS X 10.10.3 and python 2.7.6
.pyvimrc saved direct from site, no edits.

**Comment by jonathanslenders** [comment]
Thanks for reporting! I fixed it: https://github.com/jonathanslenders/pyvim/commit/34b61754c737972932b3f1902528cf7eb427d059
