### ISSUE TITLE
pyvim with pypy will not run

### ISSUE THREAD

**Issue by lunemec** [jonathanslenders/pyvim#41]
pypy seems to be missing some built-in packages and will not run:
```
pypy pyvim/entry_points/run_pyvim.py

Traceback (most recent call last):
  File "app_main.py", line 75, in run_toplevel
  File "pyvim/entry_points/run_pyvim.py", line 14, in <module>
    import docopt
ImportError: No module named docopt
```
I wanted to try pypy because python seems to be a bit laggy.

**Comment by SanketDG** [comment]
Nice catch! I guess `pip install docopt` should do the trick. We have to add `docopt` in `setup.py`

**Comment by lunemec** [comment]
docopt is installed as a dependency inside my virtualenv and system. pypy for some reason will not use it.

**Comment by lunemec** [comment]
Maybe the problem is, I was running pypy from inside python2.7 virtualenv. It seems I need to create separate virtualenv with pypy as python interpreter. But that is failing for me on some ZipImportError :(

**Comment by jonathanslenders** [comment]
Docopt is a dependency of ``ptpython``, which is a dependency of ``pyvim``. If you want, you can create a pull request to add docopt to the setup.py of ``pyvim``. That will probably be better.

**Comment by lunemec** [comment]
This is not a problem of missing docopt, I have it installed on my system, but pypy has completely different sys.path(s). It's not even trying to find it in correct directory and since I've used pypy very little I don't know what to make of this.
