### ISSUE TITLE
pyvim failed

### ISSUE THREAD

**Issue by ordinaryegi** [jonathanslenders/pyvim#59]
hello 
i had install pyvim with no error, but when execute pyvim it can't running it says
ereo@orangestar:~/Software/pyvim$ pyvim
Traceback (most recent call last):
  File "/usr/local/bin/pyvim", line 9, in <module>
    load_entry_point('pyvim==0.0.2', 'console_scripts', 'pyvim')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 521, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2632, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2312, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2318, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "build/bdist.linux-x86_64/egg/pyvim/entry_points/run_pyvim.py", line 17, in <module>
  File "build/bdist.linux-x86_64/egg/pyvim/editor.py", line 27, in <module>
  File "build/bdist.linux-x86_64/egg/pyvim/layout.py", line 17, in <module>
ImportError: No module named reactive

did i do something wrong? missing module?

regards

**Comment by jonathanslenders** [comment]
Hi @ordinaryegi  I suppose you installed ``pyvim`` through Git?
You need to check out the latest master commit of ``prompt_toolkit`` and install that. (The latest is not yet on Pypi, sorry.)

See: https://github.com/jonathanslenders/python-prompt-toolkit

Jonathan

**Comment by lillian27** [comment]
Same problem, cloned latest <code>prompt_toolkit</code> as suggested and now I get 
```
Traceback (most recent call last):
  File "/Users/lillian/Documents/Projects/slenders/base/bin/pyvim", line 9, in <module>
    load_entry_point('pyvim==0.0.2', 'console_scripts', 'pyvim')()
  File "/Users/lillian/Documents/Projects/slenders/base/lib/python2.7/site-packages/pkg_resources.py", line 356, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/Users/lillian/Documents/Projects/slenders/base/lib/python2.7/site-packages/pkg_resources.py", line 2431, in load_entry_point
    return ep.load()
  File "/Users/lillian/Documents/Projects/slenders/base/lib/python2.7/site-packages/pkg_resources.py", line 2147, in load
    ['__name__'])
ImportError: No module named pyvim.entry_points.run_pyvim
```

Suggestions?

**Comment by ordinaryegi** [comment]
same still don't found the result

2015-05-07 12:12 GMT+07:00 lillian27 <notifications@github.com>:

> Same problem, cloned latest prompt_toolkit as suggested and now I get
>
> Traceback (most recent call last):
>   File "/Users/lillian/Documents/Projects/slenders/base/bin/pyvim", line 9, in <module>
>     load_entry_point('pyvim==0.0.2', 'console_scripts', 'pyvim')()
>   File "/Users/lillian/Documents/Projects/slenders/base/lib/python2.7/site-packages/pkg_resources.py", line 356, in load_entry_point
>     return get_distribution(dist).load_entry_point(group, name)
>   File "/Users/lillian/Documents/Projects/slenders/base/lib/python2.7/site-packages/pkg_resources.py", line 2431, in load_entry_point
>     return ep.load()
>   File "/Users/lillian/Documents/Projects/slenders/base/lib/python2.7/site-packages/pkg_resources.py", line 2147, in load
>     ['__name__'])
> ImportError: No module named pyvim.entry_points.run_pyvim
>
> Suggestions?
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/jonathanslenders/pyvim/issues/59#issuecomment-99721411>
> .
>



-- 
ubuntu user # 30968

**Comment by jonathanslenders** [comment]
I guess that's something with how pyvim is installed. After installing the latest prompt-toolkit, try to run "python setup.py develop" in the pyvim repository.

But anyway, I will probably try to do a new release of both repositories on pypi this evening. (That's in about 9 hours.) That will be easier.

**Comment by lillian27** [comment]
I was able to get this working by using [pip's git interface](https://pip.pypa.io/en/latest/reference/pip_install.html#vcs-support) instead of just git clone.  I.e.
 `pip install -e git+git://githib.com/...`  

Installed `prompt_toolkit` first, then `pyvim` and everything worked.  I tried the develop flag with setup.py before this in another venv with no luck and couldn't figure out why the eggs weren't being located even though there were clearly present.  pip's git installs are supposed to be equivalent to `setup.py develop` but it seems dependences are resolved/referenced more accurately.

Anyway, really enjoying the work you are doing,  You are porting some of my favorite tools to pure python so thank you!

**Comment by jonathanslenders** [comment]
Good that you figured it out!

I did a new release on pypi. ``pip install -U pyvim`` should now give you the latest version as well.

Thanks for the complement. Pyvim is still in the early stages, but we keep improving hopefully. :)
