### ISSUE TITLE
setup.py install fails

### ISSUE THREAD

**Issue by gimu** [jonathanslenders/pyvim#62]
Installing went fine, this however occurs when trying to run pyvim:
```
Traceback (most recent call last):            
  File "/usr/bin/pyvim", line 9, in <module>
    load_entry_point('pyvim==0.0.4', 'console_scripts', 'pyvim')()
  File "/usr/lib/python3.4/site-packages/pyvim-0.0.4-py3.4.egg/pyvim/entry_points/run_pyvim.py", line 34, in run
  File "/usr/lib/python3.4/site-packages/pyvim-0.0.4-py3.4.egg/pyvim/editor.py", line 92, in __init__
  File "/usr/lib/python3.4/site-packages/pyvim-0.0.4-py3.4.egg/pyvim/editor.py", line 177, in _create_application
TypeError: __init__() got an unexpected keyword argument 'get_style'
```
Am I missing something?

**Comment by jonathanslenders** [comment]
Hi @gimu,

Thanks for pointing this out. ``pyvim`` was behind on ``prompt_toolkit``. Maybe you already had a newer version of that library?

Anyway. I just did a new pypi release of ``pyvim`` (0.0.5), pointing to the latest versions of these libraries. Does it work now? Try ``pip install -U pyvim``.

Cheers,
Jonathan

**Comment by gimu** [comment]
That indeed was the problem! It works now.

**Comment by jonathanslenders** [comment]
Great :)
