### ISSUE TITLE
Broken against newer prompt_toolkit

### ISSUE THREAD

**Issue by MarSoft** [jonathanslenders/pyvim#99]
I have just installed `pyvim` in a fresh venv (under python 3.6). And it failed to launch:
```
$ pyvim
Traceback (most recent call last):
  File "/tmp/env/bin/pyvim", line 7, in <module>
    from pyvim.entry_points.run_pyvim import run
  File "/tmp/env/lib/python3.6/site-packages/pyvim/entry_points/run_pyvim.py", line 17, in <module>
    from pyvim.editor import Editor
  File "/tmp/env/lib/python3.6/site-packages/pyvim/editor.py", line 28, in <module>
    from .key_bindings import create_key_bindings
  File "/tmp/env/lib/python3.6/site-packages/pyvim/key_bindings.py", line 4, in <module>
    from prompt_toolkit.key_binding.bindings.utils import create_handle_decorator
ModuleNotFoundError: No module named 'prompt_toolkit.key_binding.bindings.utils'
```
Looks like latest `prompt_toolkit` doesn't contain module `prompt_toolkit.key_binding.bindings.utils`, as well as that `create_handle_decorator` function (tried to grep it).
My pip freeze is like this:
```
docopt==0.6.2
prompt-toolkit==1.0.15
pyflakes==1.6.0
Pygments==2.2.0
pyvim==0.0.20
six==1.10.0
wcwidth==0.1.7
```

**Comment by MarSoft** [comment]
Here is when that module was removed (17 Dec 2016): https://github.com/jonathanslenders/python-prompt-toolkit/commit/17047496500480fc2c7653e701da0fdd5e08bfd4

**Comment by jonathanslenders** [comment]
Hi @Kentoseth and @MarSoft,

I just pushed a new version of Pyvim (0.0.21) that contains the fix. The fix was already in the repo, but not released.

FYI: at this point I'm mostly working on prompt_toolkit v2.0. This contains many improvements. Once this is finished, you can expect an improved version of Pyvim, using prompt_toolkit 2.0 as well.
